version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dgpadb
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - dgpaNet

  dgpaClient:
    container_name: dgpaclient
    image: abdulmuhsin/dgpaclient:v1
    hostname: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - dgpaNet
    volumes:
      - "./client:/client"
      - "/client/node_modules"
    ports:
      - 8080:80
  
  dgpaServer:
    container_name: dgpaserver
    image: abdulmuhsin/dgpaserver:v1
    hostname: server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      GET_HOSTS_FROM: dns
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - dgpaNet
    volumes:
      - "./server:/server"
      - "/server/node_modules"
    ports:
      - 3000:3000
networks:
  dgpaNet:
    driver: bridge
volumes:
  db:
    driver: local